name: CreateRemdDirs Tests 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_build:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      fail-fast: false
      matrix:
        compiler: ["gnu", "clang"]
        
    env:
        COMPILER: ${{ matrix.compiler }}
        BUILD_TYPE: "install"
        TEST_TYPE: "test" 

    steps:
      - name: Install prerequisite packages
        run: |
          sudo apt-get install libnetcdf-dev \
                               netcdf-bin \
                               clang

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Compile and test CreateRemdDirs
        shell: bash -lex {0}
        run: |
          ./configure ${COMPILER}
          make -j2 install
          make $TEST_TYPE

